ProjetoControleComprasWEB/ProjetoControleComprasWEB/Controllers/AdminController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Domain;
using Microsoft.AspNetCore.Mvc;
using Repository;

namespace ProjetoControleComprasWEB.Controllers
{
    public class AdminController : Controller
    {
        private readonly PedidoDAO _pedidoDAO;

        public AdminController(PedidoDAO pedidoDAO)
        {
            _pedidoDAO = pedidoDAO;
        }

        public IActionResult Index()
        {
            // Verificar quem esta Autenticado
            // pera pegar o Setor
            ViewData["NomeSetor"] = AgenteLogado.Autenticado.Setor.NomeSetor;
            ViewData["SetorId"] = AgenteLogado.Autenticado.Setor.SetorId;
            return View(_pedidoDAO.ListarTodos());
        }
    }
}

ProjetoControleComprasWEB/ProjetoControleComprasWEB/Controllers/AgenteController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Domain;
using Repository;
using Microsoft.AspNetCore.Identity;
using ProjetoControleComprasWEB.Utils;
using Microsoft.AspNetCore.Authorization;

namespace ProjetoControleComprasWEB.Controllers
{
    //[Authorize(Roles = "Administrador, Gestor")]
    public class AgenteController : Controller
    {
        private readonly AgenteDAO _agenteDAO;
        private readonly CargoDAO _cargoDAO;
        private readonly SetorDAO _setorDAO;
        private readonly UserManager<AgenteLogado> _userManager;
        private readonly SignInManager<AgenteLogado> _signInManager;
        private readonly RoleManager<IdentityRole> _roleManager;

        public AgenteController(AgenteDAO agenteDAO, CargoDAO cargoDAO, SetorDAO setorDAO, 
            UserManager<AgenteLogado> userManager, SignInManager<AgenteLogado> signInManager, 
            RoleManager<IdentityRole> roleManager)
        {
            _agenteDAO = agenteDAO;
            _cargoDAO = cargoDAO;
            _setorDAO = setorDAO;
            _userManager = userManager;
            _signInManager = signInManager;
            _roleManager = roleManager;
        }

        // GET: Agente
        public IActionResult Index()
        {
            ViewData["AgenteId"] = AgenteLogado.Autenticado.AgenteId;
            return View(_agenteDAO.ListarTodos());
        }

        // GET: Agente/Create
        public IActionResult Create()
        {
            ViewBag.Cargos = new SelectList(_cargoDAO.ListarTodos(), "CargoId", "NomeCargo");
            ViewBag.Setores = new SelectList(_setorDAO.ListarTodos(), "SetorId", "NomeSetor");
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create(Agente agente, int drpCargo, int drpSetor)
        {
            ViewBag.Cargos = new SelectList(_cargoDAO.ListarTodos(), "CargoId", "NomeCargo");
            ViewBag.Setores = new SelectList(_setorDAO.ListarTodos(), "SetorId", "NomeSetor");
            if (ModelState.IsValid) {
                agente.Senha = SenhaPadrao.CriarSenhaPadrao(agente);
                // Preencher obrigatoriamente o UserName e o Email
                AgenteLogado aLogado = new AgenteLogado
                {
                    UserName = agente.Email,
                    Email = agente.Email
                };

                IdentityResult result = await _userManager.CreateAsync(aLogado, agente.Senha);
                if (result.Succeeded)
                {
                    agente.Cargo = _cargoDAO.BuscarPorId(drpCargo);
                    agente.Setor = _setorDAO.BuscarPorId(drpSetor);

                    //-------------------atribuir role ao user------------------------------
                    var applicationRole = await _roleManager.FindByNameAsync(agente.Cargo.NomeCargo);
                    if (applicationRole != null)
                    {
                        IdentityResult roleResult = await _userManager.AddToRoleAsync(aLogado, agente.Cargo.NomeCargo);
                    }
                    //-------------------atribuir role ao user------------------------------

                    if (_agenteDAO.Cadastrar(agente))
                    {
                        return RedirectToAction("Index");
                    }
                }
                AdicionarErros(result);
            }
            ModelState.AddModelError("","Selecione um Cargo e um Setor!");
            return View();
        }

        private void AdicionarErros(IdentityResult result)
        {
            foreach (var erro in result.Errors)
            {
                ModelState.AddModelError("", erro.Description);
            }
        }

        // GET: Agente/Edit/5
        public IActionResult Edit(string usuario, int id)
        {
            ViewBag.Cargos = new SelectList(_cargoDAO.ListarTodos(), "CargoId", "NomeCargo");
            ViewBag.Setores = new SelectList(_setorDAO.ListarTodos(), "SetorId", "NomeSetor");

            if (string.IsNullOrEmpty(usuario))
            {
                if (!AgenteLogado.Autenticado.Cargo.NomeCargo.Equals("Usuario"))
                {
                    ViewData["usuario"] = "false";
                }    
            }
            else
            {
                ViewData["usuario"] = usuario;
            }

            if (AgenteLogado.Autenticado.Cargo.NomeCargo.Equals("Usuario"))
            {
                id = AgenteLogado.Autenticado.AgenteId;
            }
            return View(_agenteDAO.BuscarPorId(id));
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(Agente agente, int drpCargo, int drpSetor)
        {
            ViewBag.Cargos = new SelectList(_cargoDAO.ListarTodos(), "CargoId", "NomeCargo");
            ViewBag.Setores = new SelectList(_setorDAO.ListarTodos(), "SetorId", "NomeSetor");
            agente.Cargo = _cargoDAO.BuscarPorId(drpCargo);
            agente.Setor = _setorDAO.BuscarPorId(drpSetor);

            // Fazer Logout do Agente
            //await _signInManager.SignOutAsync();

            // Fazer update do Agente
            if (_agenteDAO.Editar(agente))
            {
                if (AgenteLogado.Autenticado.Cargo.NomeCargo.Equals("Usuario"))
                {
                    return RedirectToAction("Index", "Usuario");
                }
                return RedirectToAction("Index");
            }
            return View(agente);
        }

        // GET: Agente/Delete/5
        public IActionResult Delete(int id)
        {
            _agenteDAO.Deletar(_agenteDAO.BuscarPorId(id));
            return RedirectToAction(nameof(Index));
        }
    }
}

ProjetoControleComprasWEB/ProjetoControleComprasWEB/Controllers/CargoController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Domain;
using Repository;

namespace ProjetoControleComprasWEB.Controllers
{
    public class CargoController : Controller
    {
        private readonly CargoDAO _cargoDAO;

        public CargoController(CargoDAO cargoDAO)
        {
            _cargoDAO = cargoDAO;
        }

        // GET: Cargo
        public IActionResult Index()
        {
            return View(_cargoDAO.ListarTodos());
        }
        
        // GET: Cargo/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: Cargo/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Create(Cargo cargo)
        {
            if (ModelState.IsValid)
            {
                if (_cargoDAO.Cadastrar(cargo))
                {
                    return RedirectToAction(nameof(Index), nameof(Cargo));
                }
                ModelState.AddModelError("","Esse Cargo ja Existe!");
            }
            return View(cargo);
        }

        // GET: Cargo/Edit/5
        public IActionResult Edit(int id)
        {
            return View(_cargoDAO.BuscarPorId(id));
        }

        // POST: Cargo/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Edit(Cargo cargo)
        {
            if (ModelState.IsValid)
            {
                if (_cargoDAO.Editar(cargo))
                {
                    return RedirectToAction(nameof(Index));
                }
                ModelState.AddModelError("", "Esse Cargo ja Existe!");
            }
            return View(cargo);
        }
        
        // GET: Cargo/Delete/5
        public IActionResult Delete(int id)
        {     
            _cargoDAO.Deletar(_cargoDAO.BuscarPorId(id));
            return RedirectToAction(nameof(Index));
        }
    }
}

ProjetoControleComprasWEB/ProjetoControleComprasWEB/Controllers/SetorController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Domain;
using Repository;

namespace ProjetoControleComprasWEB.Controllers
{
    public class SetorController : Controller
    {
        private readonly SetorDAO _setorDAO;

        public SetorController(SetorDAO setorDAO)
        {
            _setorDAO = setorDAO;
        }

        // GET: Setor
        public IActionResult Index()
        {
            return View(_setorDAO.ListarTodos());
        }

        // GET: Setor/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: Setor/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Create(Setor setor)
        {
            if (ModelState.IsValid)
            {
                if (_setorDAO.Cadastrar(setor))
                {
                    return RedirectToAction(nameof(Index));
                }
                ModelState.AddModelError("","Esse Setor ja Existe!");
            }
            return View(setor);
        }

        // GET: Setor/Edit/5
        public IActionResult Edit(int id)
        {
            return View(_setorDAO.BuscarPorId(id));
        }

        // POST: Setor/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Edit(Setor setor)
        {
            if (ModelState.IsValid)
            {
                if (_setorDAO.Editar(setor))
                {
                    return RedirectToAction(nameof(Index));
                }
                ModelState.AddModelError("", "Esse Setor ja Existe!");
            }
            return View(setor);
        }

        // GET: Setor/Delete/5
        public IActionResult Delete(int id)
        {
            _setorDAO.Deletar(_setorDAO.BuscarPorId(id));
            return RedirectToAction(nameof(Index));
        }
    }
}

ProjetoControleComprasWEB/ProjetoControleComprasWEB/Views/Shared/_Layout.cshtml
@inject Microsoft.AspNetCore.Identity.UserManager<AgenteLogado> UserManager
@inject Microsoft.AspNetCore.Identity.SignInManager<AgenteLogado> SignInManager

@{
    var nomeSetor = ViewData["NomeSetor"];
}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>@ViewBag.Title</title>
    <link href="~/css/bootstrap.min.css" rel="stylesheet" />
</head>
<body>

    @* Barra de Navegação *@
    <nav class="navbar navbar-expand-lg navbar-dark bg-primary">
        <a class="navbar-brand" href="#">Controle Compras</a>
        <div class="collapse navbar-collapse" id="navbarColor01">
            <ul class="navbar-nav mr-auto">
                @if (SignInManager.IsSignedIn(User)) // Se usuario estiver autenticado
                {
                    // LOGADO Como ADMIN
                    @if (await UserManager.IsInRoleAsync(await UserManager.GetUserAsync(User), "Administrador"))
                    {
                        <li class="nav-item active">
                            <a class="nav-link" asp-action="Index" asp-controller="Admin">Home</a>
                        </li>

                        <li class="nav-item dropdown active">
                            <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                                Pedidos
                            </a>
                            <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                                <a class="dropdown-item" asp-action="Create" asp-controller="Pedido">Novo Pedido</a>
                                <a class="dropdown-item" asp-action="PedidosParaValidar" asp-controller="Pedido"
                                   asp-route-setorId="@ViewData["SetorId"]" asp-route-nomeSetor="@nomeSetor">Validar Pedidos</a>
                                <a class="dropdown-item" asp-action="ListPedidosValidados" asp-controller="Pedido"
                                   asp-route-setorId="@ViewData["SetorId"]" asp-route-nomeSetor="@nomeSetor">Consultar Pedidos Validados</a>
                                <a class="dropdown-item" asp-action="ListPedidosOrcados" asp-controller="Pedido"
                                   asp-route-setorId="@ViewData["SetorId"]" asp-route-nomeSetor="@nomeSetor">Consultar Pedidos Orçados</a>
                            </div>
                        </li>

                        <li class="nav-item active">
                            <a class="nav-link" asp-action="Index" asp-controller="Agente">Gerenciar Agentes</a>
                        </li>
                        <li class="nav-item active">
                            <a class="nav-link" asp-action="Index" asp-controller="Cargo">Gerenciar Cargos</a>
                        </li>
                        <li class="nav-item active">
                            <a class="nav-link" asp-action="Index" asp-controller="Setor">Gerenciar Setores</a>
                        </li>
                        <li class="nav-item active">
                            <a class="nav-link" asp-action="Index" asp-controller="Produto">Gerenciar Produtos</a>
                        </li>
                    }

                    // LOGADO Como GESTOR
                    @if (await UserManager.IsInRoleAsync(await UserManager.GetUserAsync(User), "Gestor"))
                    {
                        <li class="nav-item active">
                            <a class="nav-link" asp-action="Index" asp-controller="Gestor">Home</a>
                        </li>
                        <li class="nav-item active">
                            <a class="nav-link" asp-action="Create" asp-controller="Pedido">Novo Pedido</a>
                        </li>
                        <li class="nav-item active">
                            <a class="nav-link" asp-action="Index" asp-controller="Agente">Gerenciar Agentes</a>
                        </li>
                    }

                    // LOGADO Como USURAIO
                    @if (await UserManager.IsInRoleAsync(await UserManager.GetUserAsync(User), "Usuario"))
                    {
                        <li class="nav-item active">
                            <a class="nav-link" asp-action="Index" asp-controller="Usuario">Home</a>
                        </li>
                        <li class="nav-item active">
                            <a class="nav-link" asp-action="Edit" asp-controller="Agente" asp-route-usuario="true" >Editar meus Dados</a>
                        </li>
                    }

                    <a class="nav-link active" href="#">
                        Olá, @UserManager.GetUserName(User)
                    </a>
                    <li class="nav-item active my-2 my-sm-0">
                        <a class="nav-link" asp-action="Logout" asp-controller="Login">Logout</a>
                    </li>
                }
                else // usuario sem Logar
                {
                    <li class="nav-item active">
                        <a class="nav-link" asp-action="Login" asp-controller="Login">Login</a>
                    </li>
                }
            </ul>
        </div>
    </nav>
    @* Barra de Navegação *@

    @* Conteúdo *@
    <div class="container" style="margin-top:30px;margin-bottom:30px">
        @RenderBody()
    </div>
    @* Conteúdo *@

    @* Rodapé *@
    <hr /> <!-- Linha -->
    <footer>
        <p style="text-align:center">&copy; @DateTime.Now.Year - Desenvolvido por Patrick S. Luz e Maurício Kreling</p>
    </footer>
    @* Rodapé *@
   
    <script src="https://code.jquery.com/jquery-3.4.1.slim.min.js" integrity="sha384-J6qa4849blE2+poT4WnyKhv5vZF5SrPo0iEjwBvKU7imGFAV0wwj1yYfoRSJoZ+n" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js" integrity="sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6" crossorigin="anonymous"></script>

</body>
</html>